### ISSUE TITLE
Failing with TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by gnsudhakar** [hnajjar3/SwingTradingBacktesting#1]
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 167, in <module>
    main()
  File "/usr/src/app/main.py", line 141, in main
    technical_data = fetch_technical_data(ticker, start_date, end_date, args.resample_interval, logarithmic=False)
  File "/usr/src/app/main.py", line 33, in fetch_technical_data
    data['MACD'] = macd['MACD_12_26_9']
TypeError: 'NoneType' object is not subscriptable

**Comment by mapelo** [comment]
The same typeerror: 'NoneType' object is not subscriptable

python3 main.py -t AAPL -d 2014-01-01:2024-08-27
[*********************100%***********************]  1 of 1 completed
Traceback (most recent call last):
  File "SwingTradingBacktesting/main.py", line 167, in <module>
    main()
    ~~~~^^
  File "SwingTradingBacktesting/main.py", line 141, in main
    technical_data = fetch_technical_data(ticker, start_date, end_date, args.resample_interval, logarithmic=False)
  File "SwingTradingBacktesting/main.py", line 33, in fetch_technical_data
    data['MACD'] = macd['MACD_12_26_9']
                   ~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable



With this change:

    # Calculate MACD and check if it is valid
    macd = ta.macd(data['Close'])
    if macd is not None:
        data['MACD'] = macd['MACD_12_26_9']
        data['MACD_Signal'] = macd['MACDs_12_26_9']
        data['MACD_Hist'] = macd['MACDh_12_26_9']
    else:
        print("Error: can't calculate MACD.")
        data['MACD'] = data['MACD_Signal'] = data['MACD_Hist'] = np.nan



python3 main.py -t AAPL -d 2014-01-01:2024-08-27
[*********************100%***********************]  1 of 1 completed
Error: can't calculate MACD.
Price           Close       High        Low       Open     Volume   RSI MACD MACD_Signal MACD_Hist   CCI
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL                                       
Date                                                                                                    
2014-01-02  17.234297  17.355812  17.199712  17.313750  234684800  None  NaN         NaN       NaN  None
2014-01-03  16.855738  17.252064  16.838600  17.225892  392467600  None  NaN         NaN       NaN  None
2014-01-06  16.947647  17.037069  16.625787  16.745745  412610800  None  NaN         NaN       NaN  None
2014-01-07  16.826447  17.010900  16.760392  16.959802  317209200  None  NaN         NaN       NaN  None
2014-01-08  16.933002  16.998433  16.784380  16.788118  258529600  None  NaN         NaN       NaN  None
